version: '3'
services:
  servi-protocol-backend:
    image: movies-management-api/movies-management-api:0.0.1
    ports:
      - "3000:3000"
    restart: always
    environment:
      MONGO_DB_ATLAS: ${MONGO_DB_ATLAS}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
